language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

env:
  - GO111MODULE=on

before_install:
  - GO111MODULE=off go get -u honnef.co/go/tools/cmd/staticcheck
  - go get -u github.com/codegangsta/negroni
  - go get -u github.com/alecthomas/gometalinter
  - go get -u github.com/google/uuid

install:
  - go mod download

script:
  - staticcheck
  - go test -v -race -tags=integration

